docker_base_image: "debian:bullseye"
spack_gcc:
  # Whether to build the specified gcc via spack or assume existance.
  build: true
  # Version to use as compiler for spack build.
  version: "11.2.0"
